require "rake/testtask"

task :default => :test

desc "Say hello"
task :hello do
  puts "hello world"
end

desc 'Run tests'
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/**/*_test.rb']
end

task :app do
  sh "ruby lib/series_challenge.rb"
end
